//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppCRUDEF.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Employee name can't be blank")]
        [Display(Name = "Please Enter the employee Name")]
        [MaxLength(50, ErrorMessage = "Not more than 50 alphabets")]
        public string Name { get; set; }

        [Required]
        [Display(Name = "Joining Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> JoinDate { get; set; }

        [EmailAddress]
        [Display(Name = "Email Address")]
        public string Email { get; set; }

        [Phone]
        [Required]
        [Display(Name = "Cell Phone Number")]
        [MinLength(2, ErrorMessage = "Minimum 2 Digits")]
        [MaxLength(11, ErrorMessage = "Maximum 11 Digits")]
        public string Cell { get; set; }

        [Range(1000, 60000, ErrorMessage = "Salary range can be between 1000 to 60000")]
        public Nullable<double> Salary { get; set; }

        [Required]
        public string Designation { get; set; }
    }

    public enum Ranks
    {
        CEO,
        CTO,
        HR,
        Manager,
        MTO,
        Coder
    }
}