//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication8.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class student
    {
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public double Cgpa { get; set; }
        [Required]
        [DataType(DataType.Date)]
        public string Admissiondate { get; set; }
        [Required]
        public int DepartmentId { get; set; }
    
        public virtual department department { get; set; }
    }
}
